version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs: # a collection of steps
  build:
    # Remove if parallelism is not desired
    parallelism: 2
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
    docker: # run the steps with Docker
      - image: circleci/openjdk:jdk-14.0.1.7-hotspot # ...with this image as the primary container; this is where all `steps` will run

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
